#setenv script_keepwork true
#fail ucmd godebugtester run -work main.go

#fail ucmd godebugtester run -syncsend main.go
fail ucmd godebugtester run main.go
contains stdout  "recv: true=(3 == 3)"
#fail contains stdout  "start"

-- go.mod --
module mod1
-- main.go --
package main
func init(){
	go fn(3)
}
func main() {
	// the recover is inserted here, but the panic is from init func
	
	println("start")
	select{} // block
}
func fn(i int){
	println("fn",i)
	if i==3{
		panic("!")
	}
}
