#setenv script_keepwork true
#godebugtester run -work main1.go

fail godebugtester run main1.go
contains error "context deadline exceeded"

-- go.mod --
module main
-- main1.go --
package main
import "main/fa"
func main(){
	fa.Fa()
	println(1)
}
-- fa/fa.go --
package fa
func init(){
	panic("fa!") // early panic before debug connect
}
func Fa(){
	println(2)
}
